name: Build and deploy

on:
    push:
        branches:
            - deployment # Trigger the workflow on push to the deployment branch
    workflow_dispatch:
        inputs:
            version:
                description: "Commit hash or tag to roll back to (leave empty for latest push)"
                required: false
                type: string
jobs:
    deploy:
        defaults:
            run:
                working-directory: test # Set the working directory for the test job
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              # with:
              #     ref: ${{ github.event.inputs.version || 'main' }}
              #     fetch-depth: 0 # Fetch all history for all branches and tags

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20" # Specify the Node.js version

            - name: Install dependencies
              run: npm install

            - name: Build Angular app
              run: |
                  echo "building app"
                  npm run build

            - name: Stop IIS Site
              run: |
                  echo "stopping IIS server"
                  Stop-IISSite -name "angular app" -confirm:$false
              shell: powershell

            - name: Backup IIS Directory
              run: |
                  echo "Making backup"
                  Copy-Item -Recurse -Path "C:\iisServer\angular" -Destination "C:\iisServer\angular-$(Get-Date -Format 'dd-MM-yyyy')"
              shell: powershell

            - name: deploy
              run: |
                  echo "deploying"
                  Copy-Item -r dist\test\browser\* C:\iisServer\angular\
              shell: powershell

            - name: Start IIS Site
              run: |
                  echo "starting IIS server"
                  Start-IISSite -Name "angular app"
              shell: powershell
