name: Reusable steps (AKA composite action)
description: Demonstrate how to use reusable steps in a workflow

inputs:
    pathMainFolderToDeploy:
        description: "Input to the reusable workflow"
        required: true
    nameProject:
        required: true
    pathToBuildFolder:
        required: true
outputs:
    # Map the action output(s) to step output(s)
    reusable_output:
        description: "Output from the reusable workflow"
        value: ${{ steps.process-step.outputs.step_output }}

runs:
    using: "composite"
    steps:
        - name: Process reusable input
          id: process-step
          shell: bash # Must explicitly specify the shell for each step. https://github.com/orgs/community/discussions/18597
          run: |
              echo "reusable_input=${{ inputs.reusable_input }}"
              echo "HELLO_WORLD_SECRET=${HELLO_WORLD_SECRET}"
              echo "step_output=${{ inputs.reusable_input }}_processed" >> $GITHUB_OUTPUT
        - name: Process file
          shell: bash # Must explicitly specify the shell for each step. https://github.com/orgs/community/discussions/18597
          run: |
              echo "Processing file: ${{ inputs.filename }}"
              echo "file processed" >> ${{ inputs.filename }}
